import type { Metadata } from "next";
import "@/styles/global.css";
import localFont from "next/font/local";
import ProfileModal from "@/components/modal/Modal";
import Container from "@/elements/container/Container";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const containerClassName = location.pathname === SCREEN.MAP ? "mapContainer" : "container";
  // TODO: classNmae 전역에서 어떻게 사용할지

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Container className="container">{children}</Container>
        {/* 전역 ProfileModal */}
        <ProfileModal />
      </body>
    </html>
  );
}
