import type { Metadata } from "next";
import "@/styles/global.css";
import localFont from "next/font/local";
import CustomeModal from "@/components/modal/Modal";

const geistSans = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Thin.woff",
      weight: "100",
    },
    {
      path: "./fonts/Pretendard-Light.woff",
      weight: "300",
    },
    {
      path: "./fonts/Pretendard-Regular.woff",
      weight: "400",
    },
    {
      path: "./fonts/Pretendard-Medium.woff",
      weight: "500",
    },
    {
      path: "./fonts/Pretendard-Bold.woff",
      weight: "700",
    },
    {
      path: "./fonts/Pretendard-Black.woff",
      weight: "900",
    },
  ],
  variable: "--font-weight-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} `}>
      <body>
        {children}
        <CustomeModal />
      </body>
    </html>
  );
}
